# Generated by Django 2.2.12 on 2020-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('skills', models.TextField()),
                ('city', models.CharField(max_length=300)),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
