# Generated by Django 2.2.12 on 2020-04-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='reviews',
        ),
    ]
