# Generated by Django 2.2.12 on 2020-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='learn', max_length=30),
        ),
        migrations.AddField(
            model_name='skill',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
